[build]
  command = "npm install && npm run build"
  publish = ".next"
  functions = ".next/server"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_ENV = "production"
  # Force installation of peer dependencies
  NPM_FLAGS = "--legacy-peer-deps --force"
  # Add environment variable references (no values)
  CDP_API_KEY_ID = ""
  CDP_API_KEY_SECRET = ""
  CDP_WALLET_SECRET = ""
  NETWORK_ID = "base-sepolia"
  WHATSAPP_ACCESS_TOKEN = ""
  WHATSAPP_PHONE_NUMBER_ID = ""
  WHATSAPP_VERIFY_TOKEN = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Functions configuration
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@coinbase/cdp-sdk", "jose"]
  included_files = [".env.local", ".env.production"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
