[build]
  command = "npm run build"
  publish = ".next"
  functions = ".next/server"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@coinbase/cdp-sdk", "jose"]
  included_files = [".env.local"]

# Add environment variables explicitly for functions
[functions.environment]
  # This ensures environment variables are available in the serverless functions
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
